GC-5771　faq
weseek/growi-docs pull request #138
Opened 2020-08-27 08:20 UTC by fujita-kazuki

2020-09-17 10:11 UTC, yuki-takei requested changes

2020-09-17 10:11 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +| ユーザー | Users | ユーザー。(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。また、アーカイブデータをインポートするユーザー固有のIDとエクスポートするユーザ固有のIDが同一のものである場合、エラーが発生しアーカイブデータを正常に移管できない為異なったユーザ固有のIDを設定することが必要です。ここでのユーザー固有のIDとはユーザー名やメールアドレス等の
この行は元に戻して、代わりに *1 と *2 を追加してください。

2020-09-17 10:11 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +[^*1]: ユーザーデータをバックアップ/リストアする場合、現在の'PASSWORD_SEED'を新しいGROWIシステムにセットすることを忘れないでください。さもなくば、ユーザーがパスワードでログインできなくなります。現在の'PASSWORD_SEED'はエクスポートされるZIPファイル中のmeta.jsonに保存されます。しかし、この方法には不確実な点があり、より確実なPASSWORD_S
*1 は元に戻してください。

*2 は、https://github.com/weseek/growi-docs/pull/143/files#r490125763 の内容を転記してください。

2020-09-17 10:11 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +3. エクスポートが完了すると[エクスポートされたアーカイブリスト]に先ほど作成したアーカイブデータが追加されるので、リスト右部分の設定マークのドロップダウンから[ダウンロード]をクリックし、ダウンロードしてください。
https://github.com/weseek/growi-docs/pull/143/files#r490126236 の内容を転記してください。

2020-09-18 08:51 UTC, yuki-takei requested changes

2020-09-18 08:51 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +3. エクスポートが完了すると[エクスポートされたアーカイブリスト]に先ほど作成したアーカイブデータが追加されます。リスト右部分の設定マークのドロップダウンから[ダウンロード]をクリックし、ダウンロードしてください。
こちらはOK

2020-09-18 08:51 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +[^*1]: ユーザーデータをバックアップ/リストアする場合、現在の'PASSWORD_SEED'を新しいGROWIシステムにセットすることを忘れないでください。さもなくば、ユーザーがパスワードでログインできなくなります。現在の'PASSWORD_SEED'はエクスポートされるZIPファイル中のmeta.jsonに保存されます。
この行はOKです。

2020-09-18 08:51 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +インポート操作を行う管理者ユーザーの username が admin1 だった場合、エクスポートされた旧環境のデータ内に同じ admin1 を username とするユーザーが存在すると、正常にインポートすることができません。また、 email でも同様の挙動となります。そのため、インポート操作を行うときは、旧環境のデータには存在しないユーザーを新たに作成することをお勧めします。
32,33行目をまとめて *2 として、*1とは別の脚注にしてください。

2020-09-25 04:00 UTC, Yohei-Shiina commented on docs/ja/admin-guide/management-cookbook/export.md
> +| ユーザー | Users | ユーザー。(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1])(ユーザーデータのインポートには注意が必要です。[^*2])
テーブルを閉じるバーが足りない

2020-09-25 04:02 UTC, Yohei-Shiina commented on docs/ja/admin-guide/management-cookbook/export.md
> +| ユーザー | Users | ユーザー。(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1])(ユーザーデータのインポートには注意が必要です。[^*2])
(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1])(ユーザーデータのインポートには注意が必要です。[^*2]) 

を

(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1] ユーザーデータのインポートには注意が必要です。[^*2])

2020-09-25 04:44 UTC, Yohei-Shiina commented on docs/ja/admin-guide/management-cookbook/export.md
> +| ユーザー | Users | ユーザー。(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1])(ユーザーデータのインポートには注意が必要です。[^*2])
[^*1] のリンク先変じゃない？
書き終わったらレビュー出す前にまず動作確認しよう

2020-09-25 07:20 UTC, fujita-kazuki commented on docs/ja/admin-guide/management-cookbook/export.md
> +| ユーザー | Users | ユーザー。(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1])(ユーザーデータのインポートには注意が必要です。[^*2])
レビューありがとうございます。

[^*1] のリンク先は、githubから飛ぶと404になるみたいなのですが、
それ以外の件で変でしょうか？
growi docsではリンク先もちゃんとページ下部に飛ぶようになっています！
[^*2]についてなのですが、github上ではリンクに飛ぶように認識されていないような表示になっていますが[^*1]と全く同じように書いているのでgrowi docsに反映した時点で適用されるものと思います。

2020-09-25 07:21 UTC, fujita-kazuki commented on docs/ja/admin-guide/management-cookbook/export.md
> +| ユーザー | Users | ユーザー。(注意: 環境変数 `PASSWORD_SEED` を設定する必要があります。[^*1])(ユーザーデータのインポートには注意が必要です。[^*2])
aa

2021-01-12 09:17 UTC, closed without merging