Imprv/write about import and export on multi app
weseek/growi-docs pull request #156
Opened 2020-11-27 04:41 UTC by yusuketk

2020-11-27 04:43 UTC, yusuketk commented on docs/ja/admin-guide/management-cookbook/export.md
> +| <div style="white-space: nowrap;">カテゴリー</div>| MongoDB Collection 名 | 説明 |
ここは自動補正です（本タスクとは関係なし)

2020-11-27 07:40 UTC, yuki-takei requested changes

2020-11-27 07:40 UTC, yuki-takei commented on docs/ja/admin-guide/admin-cookbook/loadbalance.md
> +GROWI サーバーをロードバランスしている場合、以下のデータは GROWI 間で共有されないためアクセスできないことがあります。
- danger alert を使う

> インポート・エクスポートのデータはファイルシステムを利用するため、GROWI サーバーをロードバランスしている場合は正常動作しない可能性があります

に変更。

2020-11-27 07:40 UTC, yuki-takei commented on docs/ja/admin-guide/admin-cookbook/loadbalance.md
> +そのためデータインポートではインポートの実行、データアーカイブではアーカイブファイルのダウンロードを一度のアクセスでまとめて行うようにしてください。
「一度のアクセスでまとめて」と言われても意味がわからないから、ロードバランスしない環境での実施を推奨し、データバックアップ用とではアーカイブのエクスポートではなく mongodb-awesome-backup を使うよう推奨する(バックアップのドキュメントへ誘導する)。

2020-11-27 07:40 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/export.md
> +- 複数の GROWI サーバーでロードバランスしている場合、エクスポートしたアーカイブデータにアクセスできないことがあります。詳細は[こちら](../admin-cookbook/loadbalance.md#インポート・エクスポート機能に関する注意点)を確認してください。
ここの文言も danger alert にして、loadbalance.md での指示と同様に変更。

2020-11-27 07:40 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/import.md
> +- 複数の GROWI サーバーでロードバランスしている場合、アップロードしたファイルにアクセスできないことがあります。詳細は[こちら](../admin-cookbook/loadbalance.md#インポート・エクスポート機能に関する注意点)を確認してください。
ここの文言も danger alert にして、loadbalance.md での指示と同様に変更。

2020-11-27 07:40 UTC, yuki-takei commented on docs/ja/admin-guide/admin-cookbook/loadbalance.md
> +GROWI サーバーをロードバランスしている場合、以下のデータは GROWI 間で共有されないためアクセスできないことがあります。
danger alert 外で、重複にはなるがもう一度以下を書く。

> インポート・エクスポートでは、以下のデータをファイルシステム上で展開して処理します。
>  
> - データインポート画面の～
> - データアーカイブ画面の～
> 
> そのため～

2020-12-02 07:14 UTC, yusuketk commented
FB修正後

- インポート

<img width="1435" alt="Screen Shot 2020-12-02 at 16 13 20" src="https://user-images.githubusercontent.com/38426468/100840519-5be10600-34b9-11eb-9bfc-a03b2b712030.png">

- エクスポート

<img width="1435" alt="Screen Shot 2020-12-02 at 16 13 27" src="https://user-images.githubusercontent.com/38426468/100840521-5c799c80-34b9-11eb-976f-54a5adc75bad.png">

- ロードバランス

<img width="1435" alt="Screen Shot 2020-12-02 at 16 13 12" src="https://user-images.githubusercontent.com/38426468/100840515-5a174280-34b9-11eb-9533-0726803624a6.png">

2020-12-02 09:32 UTC, merged