translate loadbalance page
weseek/growi-docs pull request #157
Opened 2020-12-04 07:52 UTC by yusuketk

2020-12-04 07:54 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +
日本語分
```
## インポート・エクスポート機能に関する注意点

:::danger
インポート・エクスポートのデータはファイルシステムを利用するため、GROWI サーバーをロードバランスしている場合は正常動作しない可能性があります。
:::

インポート・エクスポートでは、以下のデータをファイルシステム上で展開して処理します。

- データインポート画面(`/admin/importer`) の 「GROWI アーカイブをインポート」にてアップロードした「GROWI アーカイブファイル」
- データアーカイブ画面(`/admin/export`) の「エクスポートされたアーカイブ」

そのためインポート・エクスポート機能はロードバランスしない環境での利用を推奨します。

また、データのバックアップを行いたい場合はアーカイブのエクスポートではなく [mongodb-awesome-backup](./mongodb-backup.md) の利用を推奨します。
```

2020-12-04 09:52 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +:::
doesn't → don't

2020-12-04 10:53 UTC, kaoritokashiki requested changes

2020-12-04 10:53 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +Data imports/exports expands the follow data on file system in the process.
Data imports/exports expand the following data on the file system in the process.

- expandsにsはいらないです
- file system にthe をつける

2020-12-04 10:53 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +:::
- doesn't operete → don't operate(三人称単数, スペルチェック注意)
- file system → the file system

In case of load balancing multiple GROWI applications,
it may not work properly because these use the file system.


三人称単数や、スペルミスはgoogleの拡張機能である「grammarly」で解決できるのでインストールお願いしたいです

2020-12-04 10:53 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +Therefore Data imports/exports is not recommended with load balancing multi apps.
- is → are
Therefore, data imports/exports are not recommended with load balancing multiple GROWI apps.

- 上に`multiple`とあったのでmulti と省略しない方がいいかなと思いました。
- 初見の私(そこまで技術に詳しくない人)からは"GROWI"をつけた方が理解しやすいと思ったのですが、なくても伝わるようでしたらなくていいと思います。

2020-12-04 10:53 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +- "Exported Archive Data" in Export Archive Data page(`/admin/export`)
- "GROWI archive file" uploaded by "Import GROWI archive" on the "Import Data" page (`/admin/importer`)

- "Exported Archive Data" on the "Export Archive Data" page (`/admin/export`)


「Import Data 」「Export Archive Data」は" で囲ってあげた方がみやすいと思います。

2020-12-04 10:53 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +If you want to create a backup, [mongodb-awesome-backup](./mongodb-backup.md) is recommended.
日本語に合わせて、より詳しく書くならこうですかね。
- If you want to back up your data,  [mongodb-awesome-backup] (./mongodb-backup.md) is recommended instead of exporting the archive.

2020-12-04 10:54 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +
ありがたいです

2020-12-04 11:11 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +:::
ありがとうございます。

2020-12-04 11:15 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +:::
提案していただいた文のit をdata imports/exportsに置き換えたものにしましたが、これで大丈夫でしょうか？

2020-12-04 11:16 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +:::
あと後述で appsとしているのでapplications→appsに変更しています。

2020-12-04 11:19 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +- "Exported Archive Data" in Export Archive Data page(`/admin/export`)
"GROWI archive file" はGROWIアプリ内で使われている"GROWI Archive File"のままにしています。

2020-12-04 11:21 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +If you want to create a backup, [mongodb-awesome-backup](./mongodb-backup.md) is recommended.
ありがとうございます
なるほど > instead of ~

2020-12-04 11:22 UTC, yusuketk commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +Therefore Data imports/exports is not recommended with load balancing multi apps.
multiple 統一が良さそうですね
自分も同じ考えなのでGROWIつけときます

2020-12-04 11:25 UTC, yusuketk commented
/ で書く場合は2者書いてるから主語は複数扱いなんですね

2020-12-07 08:58 UTC, kaoritokashiki requested changes
2者書いているというより、importsで既に複数なのでareになります。

2020-12-07 08:58 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/loadbalance.md
> +Data imports/exports expand the following data on the file system in the process.
`in the process`、不要だと思ったのですがつけている理由ってありますか??
特になければ消してください。

> 提案していただいた文のit をdata imports/exportsに置き換えたものにしましたが、これで大丈夫でしょうか？

すみません、そちらの方が正しいです。指摘ありがとうございます。

>あと後述で appsとしているのでapplications→appsに変更しています。

それで良いです。ありがとうございます。

2020-12-09 08:56 UTC, merged