Imprv/gw4725 upgrading the guide regarding attachment
weseek/growi-docs pull request #161
Opened 2020-12-17 05:42 UTC by kaoritokashiki

2020-12-17 08:36 UTC, yuki-takei requested changes

2020-12-17 08:36 UTC, yuki-takei commented on docs/en/admin-guide/admin-cookbook/attachment.md
> +Only if you need full security, Change to Relay Mode from [App settings of the Management page ](../management-cookbook/app-settings.html#appsettings-tbd).
you need じゃなく the system requires みたいなこのシステムの要求(要件)に完全なセキュリティーが入っているなら、という感じで書けないかな。

2020-12-17 08:36 UTC, yuki-takei commented on docs/en/admin-guide/admin-cookbook/attachment.md
> +In Relay Mode, the GROWI server relays communication with Cloud Service and pass the data to clients.
違和感

2020-12-17 10:12 UTC, yuki-takei requested changes

2020-12-17 10:12 UTC, yuki-takei commented on docs/en/admin-guide/admin-cookbook/attachment.md
> +Notify the client and prompt for a redirect.
## メモ

```
In the Redirect Mode, Cloud Service issues a signed URL for file references.
it notifies the client and prompts redirection.(クライアントに通知してリダイレクトを促す)
or
it prompts redirection to the client (クライアントにリダイレクトを促す) (edited) 
```

```
Cloud Service issues a signed URL for file references as a result of request from the GROWI server.
だとどうかな。
```

2020-12-18 03:31 UTC, kaoritokashiki commented on docs/en/admin-guide/admin-cookbook/attachment.md
> +In case of the system requires advanced security, change to Relay Mode from [App settings of the Management page ](../management-cookbook/app-settings.html#appsettings-tbd).
完全なセキュリティ→高度なセキュリティとしました。

2020-12-18 06:56 UTC, yuki-takei approved these changes

2020-12-18 06:56 UTC, merged