Imprv/gw5372 move slack mattermost notification to appropriate file
weseek/growi-docs pull request #171
Opened 2021-03-09 06:34 UTC by kaoritokashiki

2021-03-09 07:07 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +User Trigger Notificationの設定方法は[こちら](../management-cookbook/external-notification.html#user-trigger-notification-設定)を参照してください。
User Trigger Notificationの設定方法は、別ページの「外部ツールへの通知」に記載されているので、そこに飛ぶリンクを追加しました。

2021-03-09 10:33 UTC, yuki-takei requested changes

2021-03-09 10:33 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/external-notification.md
> +1つの GROWI につき 1つのワークスペースを登録でき、ワークスペースに属する全てのチャンネルに通知できます。
> ワークスペースに属するチャンネルのいずれかを選択して通知を行う事ができます。

2021-03-09 10:33 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/external-notification.md
> +通常、通知先のチャンネルを通知する度に入力する必要がありますが、
User Trigger Notification は、GROWI を利用するユーザーがページの編集やコメントの投稿を行う際に選択的に通知を行う事ができる機能です。基本的には通知先のチャンネルを都度入力する必要がありますが、

2021-03-09 10:33 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +1つの GROWI につき 1つのワークスペースを登録でき、ワークスペースに属する全てのチャンネルに通知できます。
- Slack 連携の方法として、Bot と Incoming Webhook の2種類の方法があることを最初に書く
- このページは通知に特化したドキュメントにならないようにする

2021-03-09 10:33 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +- **Wrbhook URL**
typo

2021-03-10 02:10 UTC, kaoritokashiki commented
ブランチ切るところを間違っていたようなので新しくPR作成しました↓
https://github.com/weseek/growi-docs/pull/173
よってcloseします。

2021-03-10 02:10 UTC, closed without merging