Imprv/how to create slash command
weseek/growi-docs pull request #174
Opened 2021-03-10 07:59 UTC by zahmis

2021-03-10 09:29 UTC, yuki-takei requested changes

2021-03-10 09:44 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +     - https:// 連携させたい GROWI のドメイン名 /\_api/v3/slack-bot
これは保存したときに自動で追加されました。
https:// ~~~ この中にスペースが存在すれば 自動で保存されるようになっています。

2021-03-10 09:44 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +       - 例 https://ff9b07497173.ngrok.io/_api/v3/slack-bot
承知しました

2021-03-10 09:45 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +- Command に /growi と入力してください。
承知しました

2021-03-11 06:33 UTC, yuki-takei requested changes

2021-03-11 06:33 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +     - https:// 連携させたい GROWI のドメイン名 /\_api/v3/slack-bot
ドキュメント(HTML)に表示されないのであればそれでよいです

2021-03-11 06:45 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +     - https:// 連携させたい GROWI のドメイン名 /\_api/v3/slack-bot
承知しました

2021-03-11 06:50 UTC, merged