Imprv/en slack integration
weseek/growi-docs pull request #182
Opened 2021-03-22 07:17 UTC by zahmis

2021-03-22 12:13 UTC, yuki-takei requested changes

2021-03-22 12:13 UTC, yuki-takei commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +![slack1](../../../ja/admin-guide/management-cookbook/images/slack1.png)
png が `/ja` の配下にあるのはおかしい。共用であれば lang のツリーの外に置くべき。

2021-03-22 16:06 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +![slack1](../../../ja/admin-guide/management-cookbook/images/slack1.png)
なるほど。
修正します

2021-03-23 02:33 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +GROWI provides two methods of Slack integration: 1. GROWI bot and 2. Incoming Webhook.
1. GROWI bots ですね。2. Incoming Webhooks

2021-03-23 04:21 UTC, kaoritokashiki requested changes

2021-03-23 04:21 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +     ![full-text-search-click-share](../../../public/assets/images/full-text-search-click-share.png)
Next とShare buttonの位置を変えたいですね。泣

2021-03-23 10:56 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +![slack1](../../../ja/admin-guide/management-cookbook/images/slack1.png)
vuepress を使用している docs をいくつか見たのですが、
共用の image は .vuepress/public/assets に置いていたのと
推奨される directory 構造から定石に従います。

2021-03-24 06:06 UTC, kaoritokashiki requested changes

2021-03-24 06:06 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Set the scope
Scope settings

2021-03-24 06:06 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Set each Request URL
ここもですね。

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +The GROWI bots is a Slack App developed by the GROWI development team. By installing it in Slack workspaces, you can not only receive notifications from GROWI, but also execute full-text searches fro
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +The Official GROWI bot is a free GROWI bot provided and operated by the GROWI development team.It is available at [slack app directory](https://wsgrowi.slack.com/apps) and anyone can use this service
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Incoming Webhook is another way to do Slack integration, but unlike GROWI bots, it is focused on notifications to Slack. It does not have many features like GROWI bots, such as full-text search from
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +### Custom bot (non-proxy) Setting
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Set the scope
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Set each Request URL
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +### Set the Official bot
🙌

2021-03-24 06:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +### Full-text search in the workspace
なるほど

2021-03-24 07:57 UTC, kaoritokashiki requested changes

2021-03-24 07:57 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +GROWI bots are a Slack App developed by the GROWI development team. By installing it in Slack workspaces, you can not only receive notifications from GROWI, but also execute full-text searches from c
a Slack App -> Slack Apps です。

2021-03-24 07:57 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Create Slack app
Create a Slack appです。

2021-03-24 08:02 UTC, merged