Imprv/external notification en
weseek/growi-docs pull request #183
Opened 2021-03-23 05:54 UTC by zahmis

2021-03-24 08:30 UTC, kaoritokashiki requested changes

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +  1. Create an IFTTT applet of your choice from the link.
違和感がありますね。

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +## User Trigger Notification Setting
Settings

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +Basically, it is necessary to enter the channel to be notified each time, but it is possible to eliminate the input by setting a default pattern.
ん

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +### How to set the default pattern
the ->  a

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Access the security settings page (/admin/notification) in the Management page.
security settings page -> Security Settings pageですね。

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +- If you want to display the default pattern on all pages, type `/*`.
please type `/*`.
pleaseつけた方が良さそうです。

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +You can configure Slack notifications to be sent out when a Wiki user performs a certain action.
a Wiki user -> a GROWI user

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Access the security settings page (/admin/notification) in the Management page.
Access toですね。

- security settings page
同上

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Click the Add Notification button on the right side of the list of notification settings.
`Add Notification` これ太文字にすべきですね。

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +- Pages that are restricted to 'only inside the group'.
`only inside the group` Onlyは大文字じゃないですかね。

2021-03-24 08:30 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +Enabling the checkbox will enable the detection of events in the following pages.
enableが続けてきているの違和感ですね。

2021-03-24 08:37 UTC, kaoritokashiki requested changes

2021-03-24 08:37 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +User Trigger Notification is a feature that allows users of GROWI to be selectively notified when they edit a page or post a comment.
`users of GROWI to be selectively notified`ここが少し助長ですね。
users of GROWI　を GROWI users とするだけでもわかりやすくなります。
が他にもっといい書き方がありそうです。

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +GROWI allows Slack notifications using an Incoming Webhook.
なるほど。
了解です

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +## User Trigger Notification Setting
🙌

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +User Trigger Notification is a feature that allows users of GROWI to be selectively notified when they edit a page or post a comment.
修正します

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +### How to set the default pattern
🙌

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Access the security settings page (/admin/notification) in the Management page.
🙌

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +- If you want to display the default pattern on all pages, type `/*`.
了解です。

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +You can configure Slack notifications to be sent out when a Wiki user performs a certain action.
🙌

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Access the security settings page (/admin/notification) in the Management page.
なるほど。承知しました。

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +Enabling the checkbox will enable the detection of events in the following pages.
確かに...
修正します

2021-03-24 08:55 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +- Pages that are restricted to 'only inside the group'.
大文字でした..

2021-03-25 02:10 UTC, kaoritokashiki requested changes

2021-03-25 02:10 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +## Type of notificaiton method
- typeは複数ですね。
- notificaiton ← スペルミスです。

2021-03-25 02:10 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +  1. click **Add Notification Settings**.
click -> 頭は大文字です。

2021-03-25 02:12 UTC, kaoritokashiki requested changes

2021-03-25 02:12 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Access the Security Settings page (/admin/notification) in the Management page.
ここも Access to

2021-03-25 03:31 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +## Type of notificaiton method
なるほど

2021-03-25 03:31 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +  1. click **Add Notification Settings**.
🙌

2021-03-25 03:31 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/external-notification.md
> +1. Access the Security Settings page (/admin/notification) in the Management page.
🙌

2021-03-25 03:32 UTC, merged