Imprv/explain how to register signing secret and bot token
weseek/growi-docs pull request #184
Opened 2021-03-29 02:45 UTC by zahmis

2021-03-29 02:47 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +
ここからが変更内容です

2021-03-29 02:47 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
ここまでが変更内容です

2021-03-29 03:59 UTC, kaoritokashiki requested changes

2021-03-29 03:59 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +1. OAuth Tokens for Your Team の Bot User Oauth Token から確認します。
ここも太文字の方が良さそうです。

2021-03-29 03:59 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +確認した Signing Secret と Bot User OAuth Token は 管理画面で入力して設定する方法と環境変数で設定する方法があります。管理画面で直接入力する方が容易です。また、環境変数と管理画面の両方に入力した場合は、管理画面で入力した値が優先されるので、管理画面での入力をおすすめします。
1. 管理画面で入力して設定する方法 と 2. 環境変数で設定する方法
の2種類の方法があります。

2021-03-29 03:59 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +   ![slack-bot-oauth-and-permissions](../../../.vuepress/public/assets/images/slack-bot-oauth-and-permissions.png)
画像のテキストを白で隠すと文字がxoxb-だけなのかなという風に見えてしまうので白以外の方がいいんじゃないかなと思いました。
黒とかどうですかね。

2021-03-29 04:01 UTC, kaoritokashiki requested changes

2021-03-29 04:01 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +   ![slack-bot-oauth-and-permissions](../../../.vuepress/public/assets/images/slack-bot-oauth-and-permissions.png)
それともDocsだとちゃんと隠れているように見えるのでしょうか

2021-03-30 03:15 UTC, zahmis commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +確認した Signing Secret と Bot User OAuth Token は 管理画面で入力して設定する方法と環境変数で設定する方法があります。管理画面で直接入力する方が容易です。また、環境変数と管理画面の両方に入力した場合は、管理画面で入力した値が優先されるので、管理画面での入力をおすすめします。
🙌

2021-03-30 04:58 UTC, merged