Imprv/explain how to register signing secret and token en
weseek/growi-docs pull request #185
Opened 2021-03-30 05:31 UTC by zahmis

2021-03-30 05:35 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Signing Secret and Bot User OAuth Token settings
ここからが変更点です。

2021-03-30 05:35 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
ここまでです。

2021-03-30 05:35 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Assign `SLACK_SIGNING_SECRET` and `SLACK_BOT_TOKEN` with the values you checked.
ここ the つけたのですが、ちょっとどっちが適切かわからなかったので教えて欲しいです。

2021-03-30 06:22 UTC, kaoritokashiki requested changes

2021-03-30 06:28 UTC, kaoritokashiki requested changes

2021-03-30 06:28 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +There are two ways to set Signing Secret and Bot User OAuth Token: 1. Set them in the Management page 2. Set them with environment variables. It is easier to set them in the Management page. Also, if
- `so we recommend setting in the Management page.`
we 使わずに `settings in the Management page is recommended`
としてください。

2021-03-31 03:00 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Assign `SLACK_SIGNING_SECRET` and `SLACK_BOT_TOKEN` with the values you checked.
😭

2021-03-31 03:00 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +There are two ways to set Signing Secret and Bot User OAuth Token: 1. Set them in the Management page 2. Set them with environment variables. It is easier to set them in the Management page. Also, if
🗒

2021-03-31 03:17 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +There are two ways to set Signing Secret and Bot User OAuth Token: 1. Set them in the Management page 2. Set them with environment variables. It is easier to set them in the Management page. Also,
二回目の変更点です。

2021-03-31 04:07 UTC, kaoritokashiki requested changes

2021-03-31 04:07 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +in case that you input values in both the Management page and environment variable, the Management page value will take a priority. That's why we recommend setting in the Management page.
`we recommend setting in the Management page.`
we 使わずに settings in the Management page is recommended
としてください。

2021-03-31 04:43 UTC, merged