5663 users guide tag
weseek/growi-docs pull request #192
Opened 2021-04-22 05:12 UTC by stevenfukase

Added English translation for Tags page

2021-04-22 11:06 UTC, kaoritokashiki requested changes

2021-04-22 11:08 UTC, kaoritokashiki requested changes

2021-04-22 11:08 UTC, kaoritokashiki commented on docs/en/guide/features/tag.md
> +Once the tags have been set up, click the Done button as shown in the image below.
ここ、Once使うと若干意味違くなりませんかね

2021-04-23 10:42 UTC, yuki-takei requested changes

2021-04-23 10:42 UTC, yuki-takei commented on docs/en/guide/features/tag.md
> +Navigate to the page where the tags are going to be added. <br/>
markdown では br タグは使わない。スペース x 2

2021-04-23 10:42 UTC, yuki-takei commented on docs/en/guide/features/tag.md
> +Hovering over the search box will display a guide when searching, as shown in the image below.
ガイドが表示されるのは hover じゃなくて focus じゃないかな

2021-04-23 12:01 UTC, yuki-takei requested changes

2021-04-23 12:01 UTC, yuki-takei commented on docs/en/guide/features/tag.md
> +Focusing over the search box will display a guide when searching, as shown in the image below.
over 不要

2021-04-23 12:02 UTC, merged