5664 hack md
weseek/growi-docs pull request #193
Opened 2021-04-26 02:46 UTC by stevenfukase

2021-04-26 04:29 UTC, kaoritokashiki requested changes

2021-04-26 04:29 UTC, kaoritokashiki commented on docs/en/guide/features/hackmd.md
> +More than one user can edit an article at the same time.
一名以上なので、一人の場合も含めたいですね。
`One or more users can ~~~`

2021-04-26 04:29 UTC, kaoritokashiki commented on docs/en/guide/features/hackmd.md
> +## Save edits
ここも-ingで統一でお願いします

2021-04-26 04:29 UTC, kaoritokashiki commented on docs/en/guide/features/hackmd.md
> +When a user presses the "Refresh" button, the edits of all users will be saved to the page.
GROWIではボタンの英語表記をUpdateにしてるので、 Updateに変更お願いします。

2021-04-26 04:29 UTC, kaoritokashiki commented on docs/en/guide/features/hackmd.md
> +The user who presses the Refresh button will switch from HackMD mode to Browse mode, while the other users will continue to edit the page.
同上でUpdateに変更お願いします。

また、ここもGROWIの表記的にBrowseではなくて View modeですね。

2021-04-26 04:29 UTC, kaoritokashiki commented on docs/en/guide/features/hackmd.md
> +![](./images/HackMD1.png)
スクリーンショットを変更する必要があります。

2021-04-27 03:58 UTC, stevenfukase commented
### 英語
![英語](https://user-images.githubusercontent.com/66785624/116183017-27b3fd80-a758-11eb-9f84-32881934b726.png)

### 日本語
![日本語](https://user-images.githubusercontent.com/66785624/116182997-21258600-a758-11eb-9c86-5e20e9d71455.png)

2021-04-27 04:48 UTC, kaoritokashiki commented
日本語のページは日本語モードでスクショをとる方がいいと思っています。
理由は、編集モードの更新ボタンが「更新」になったり「Update」になったりしてて違和感があるからです。


正直HackMDの部分ではあまり気にならないですけど、そこが統一されていないと他の項目の部分でカオスなことになりそうと思いました。
eg)「更新」ボタンを押してくださいと説明があるにもかかわらず、写真のボタンは「Update」と書かれているとか....。

2021-04-30 10:23 UTC, merged