Fix/without proxy manual en
weseek/growi-docs pull request #195
Opened 2021-04-27 06:14 UTC by zahmis

2021-04-27 06:22 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +1. In the [Create a Slack App] section, ① input the name of your app in the [App Name] field and ② select the workspace where you want to add the GROWI bots in the [Development Slack Workspace].
ここは変更してないです

2021-04-27 06:22 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +#### Before creating Slack app
元の日本語

```
 Slack app を作成する前に

GROWI 本体サーバーを立ち上げてください。後述する Event Subscription の応答に必要となります。
```

2021-04-27 06:22 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  1. When the input is complete and **Verified** is displayed, the communication from the Slack APP to the GROWI server has been successful.
元の日本語
` 1. 入力が完了し **Verified** が表示されたら、Slack APP から GROWI サーバーへの通信は成功しています。`

2021-04-27 06:49 UTC, kaoritokashiki requested changes

2021-04-27 06:49 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +1. Select **commands**,**chat: write** and **team:read**.
`**commands**, **chat:~~`
カンマの右にスペース開けてください

2021-04-27 06:49 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  1. When the input is complete and **Verified** is displayed, the communication from the Slack APP to the GROWI server has been successful.
日本語まで記載してくれるのありがたいです！

`complete` -> `completed`

2021-04-27 06:49 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Start up the GROWI main server to respond to the Event Subscription described below.
upなくて良さそうです。
`Start your GROWI main server`
ESの話を前にしていないので`the`はいらないのと`Event Subscriptions`(複数)にしてください。

2021-04-27 07:09 UTC, kaoritokashiki requested changes

2021-04-27 07:09 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  1. When the input is complete and **Verified** is displayed, the communication from the Slack APP to the GROWI server has been successful.
日本語まで記載してくれるのありがたいです！

`When the Request URL has been correctly entered, **Verified** will be displayed on the screen. It means the Slack APP and the GROWI server are connecting successfully.`
かな。

2021-04-28 16:27 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Start up the GROWI main server to respond to the Event Subscription described below.
🙌

2021-04-28 16:27 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +1. Select **commands**,**chat: write** and **team:read**.
忘れてました...

2021-04-28 16:27 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  1. When the input is complete and **Verified** is displayed, the communication from the Slack APP to the GROWI server has been successful.
ナルホド

2021-04-28 16:27 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +(TBD)
日本語側に入れたので入れました

2021-04-28 17:25 UTC, kaoritokashiki approved these changes

2021-05-06 02:58 UTC, kaoritokashiki requested changes

2021-05-06 02:58 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Start your GROWI main server to respond to the Event Subscriptions described below.
- Event Subscriptionsがうまく機能するように~~と書いた方がわかりやすい気がします。

`Start the GROWI main server so that the event subscriptions described below work properly.`

2021-05-06 07:34 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +Start your GROWI main server to respond to the Event Subscriptions described below.
🙌

2021-05-06 07:35 UTC, merged