5671 url settings
weseek/growi-docs pull request #197
Opened 2021-05-12 07:38 UTC by stevenfukase

2021-05-12 08:57 UTC, kaoritokashiki requested changes

2021-05-12 08:57 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/app-settings.md
> +## Set the site URL
似たような見出しが二つありますけど、`Site URL Settings`と`Set the site URL`とで違いってあるのでしょうか?
不要であれば片方消してください。〇〇 Settings で統一の方が良さそうです。

2021-05-12 08:57 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/app-settings.md
> +If a value is entered in the `Database` field to be edited in the admin panel, the value will be displayed in the `Database` field.
あれ、この文章っていります??

2021-05-12 08:57 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/app-settings.md
> +The following error message is displayed in the settings section of the administration screen and in the header section of the page.
`the admin page`が短くて良さそう。

2021-05-17 03:29 UTC, kaoritokashiki approved these changes

2021-05-17 08:14 UTC, yuki-takei requested changes

2021-05-17 08:14 UTC, yuki-takei commented on docs/en/admin-guide/management-cookbook/app-settings.md
> +If a DNS record such as `growi.hogehoge.com` has been specified as the destination for a custom domain, set it here.
example.com で書く。
日本語の方も直してください。

2021-05-18 01:23 UTC, merged