Fix/add explanation how to test to slack en ver
weseek/growi-docs pull request #215
Opened 2021-06-21 05:30 UTC by zahmis

2021-06-21 07:22 UTC, kaoritokashiki requested changes

2021-06-21 07:22 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +2. Click **Test**.
`Click on the **Test** button.`
に修正お願いします。

2021-06-21 07:22 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  **Successfully sent to Slack workspace** will be displayed at Logs. Green check marks will appear in red circles. Check the channel to which you invited GROWI-Bot.
check marks -> checkmarks

2021-06-21 07:22 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  - In case of Failed
`In case of failure` でお願いします。

2021-06-21 07:22 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +    if **Channel_not_found** will be displayed, you don't invite GROWI-Bot to the slack channel or input wrong channel. Make sure that GROWI-Bot has been invited to the slack channel, and input the c
```
if you have not invited GROWI-Bot to the slack channel or inputted the wrong channel, **Channel_not_found** error will be displayed in the logs. Please make sure that GROWI-Bot has been invited to the Slack channel, and the channel name has been inputted appropriately.
```
かな。

2021-06-21 07:56 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +    if **Channel_not_found** will be displayed, you don't invite GROWI-Bot to the slack channel or input wrong channel. Make sure that GROWI-Bot has been invited to the slack channel, and input the c
ナルホド

2021-06-21 08:04 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  - In case of failure
fb 箇所

2021-06-21 08:04 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +    if you have not invited GROWI-Bot to the Slack channel or inputted the wrong channel, **Channel_not_found** error will be displayed in the logs. Please make sure that GROWI-Bot has been invited t
fb 箇所

2021-06-21 08:04 UTC, zahmis commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +2. Click on the **Test** button.
fb 箇所

2021-06-22 04:04 UTC, kaoritokashiki requested changes

2021-06-22 04:04 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration.md
> +  **Successfully sent to Slack workspace** will be displayed at Logs. Green checkmarks will appear in red circles. Check the channel to which you invited GROWI-Bot.
- これクォーテーションつけた方が良さそうですね。
`'**Successfully sent to Slack workspace**'` かな

2021-06-22 04:23 UTC, merged