Imprv/5681 growi archive
weseek/growi-docs pull request #244
Opened 2021-06-30 07:35 UTC by stevenfukase

Eng. ver. for growi import
![localhost_8080_en_admin-guide_management-cookbook_import html(Full HD)](https://user-images.githubusercontent.com/66785624/123920574-10e09000-d9c1-11eb-83d7-b1a1b7d97dfb.png)

2021-07-02 04:41 UTC, kaoritokashiki requested changes

2021-07-02 04:41 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/import.md
> +  - The Config collection can only be imported in this mode.
- can only be imported
-> can only be selected

2021-07-05 08:25 UTC, yuki-takei requested changes

2021-07-05 08:25 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/import.md
> +GROWI v4.2.21 現在では、GROWI、 esa.io、Qiita:Team のデータをインポートする機能をサポートしています。
「v3.7.2 以降で」という表現に変えよう。en も同様。

2021-07-05 08:39 UTC, merged