Fix/bot manual composition
weseek/growi-docs pull request #251
Opened 2021-07-07 10:43 UTC by kaoritokashiki

2021-07-07 10:46 UTC, kaoritokashiki commented on docs/.vuepress/config.js
> +                '/ja/admin-guide/management-cookbook/grw-custom-bot-with-proxy-settings.md',
README.はここには指定できないので、
配下に新しく各種bot設定用のパスを指定しました。

2021-07-07 10:47 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration.md
> +設定方法は[こちら](/ja/admin-guide/management-cookbook/grw-custom-bot-without-proxy-settings.md)をご覧ください。
各botの設定ページに飛ぶようにしました。

2021-07-07 14:27 UTC, yuki-takei requested changes

2021-07-07 14:27 UTC, yuki-takei commented on docs/.vuepress/config.js
> +                '/ja/admin-guide/management-cookbook/grw-custom-bot-with-proxy-settings.md',
これじゃない感…

2021-07-09 06:17 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration/README.md
> +![diagram-for-official-bot](/assets/images/slack-bot-outline-official.png)
path を相対パスではなく絶対パスで指定しました。

2021-07-09 06:18 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/setup-search-system.md
> +  ![](/assets/images/setup-search-system1.png)
このファイルのパスもエラーが出ていたのでついでに修正しました。

2021-07-09 06:22 UTC, kaoritokashiki commented on docs/.vuepress/config.js
> +                },
なるほどです。ありがとうございます。

2021-07-09 08:31 UTC, yuki-takei commented
各タイプの設定ページにも概念図を入れてください。

2021-07-12 02:07 UTC, kaoritokashiki commented
各設定ページにて概念図を挿入しました。

2021-07-12 02:09 UTC, merged