find out what needs to be fixed!!
weseek/growi-docs pull request #254
Opened 2021-07-12 06:48 UTC by miya

## 概要
修正すべき箇所にコメントをつけました。

2021-07-12 07:22 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +<!-- TODO: GW-6770  大文字にする（to -> To）-->
to これは小文字のままで大丈夫です!

2021-07-12 07:31 UTC, kaoritokashiki requested changes

2021-07-12 07:31 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +<!-- TODO: GW-6770  大文字にする（to -> To）-->
to これは英語のルール的に小文字のままで大丈夫です!
本当はアコーディオンの方を変える必要があるけど、その場合、
docsに挿入されている大量の画像を変更しなければいけないのでそのままで良さそうです。

2021-07-12 07:31 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +  <!-- TODO: GW-6770 この文言は消す -->
👍

2021-07-12 07:31 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +    <!-- TODO: GW-6770 現在の Official bot のアイコンは GROWI bot 君になっているので変えた方がよさそう？-->
👍

2021-07-13 06:46 UTC, kaoritokashiki requested changes

2021-07-13 06:46 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration/custom-bot-with-proxy-settings.md
>              ![slack-bot-test-success-at-slack-app](/assets/images/slack-bot-test-success-at-slack-app.png)
あ、オフィシャルとカスタムで画像を分ける必要はないですね。
一応、カスタムを使う人にもbot君のイメージ画像はDocsにて提供しているので！

2021-07-13 06:46 UTC, kaoritokashiki commented on docs/ja/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +   ![slack-bot-test-success](/assets/images/slack-bot-test-success-official-at-slack-app.png)
「bot君を使用した画像」に差し替えだけで良いと思います。(officialかどうかで画像を分ける必要はない)

2021-07-13 06:53 UTC, kaoritokashiki commented on docs/en/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +    ![slack-bot-test-success](/assets/images/slack-bot-test-success-official.png)
これって複数にしている理由ありますか??

2021-07-13 10:35 UTC, miya commented on docs/en/admin-guide/management-cookbook/slack-integration/official-bot-settings.md
> +    ![slack-bot-test-success](/assets/images/slack-bot-test-success-official.png)
間違えて入れてしまったみたいです！消しておきます！

2021-07-16 04:18 UTC, merged