add english guide for custom rate limit
weseek/growi-docs pull request #312
Opened 2022-08-03 13:15 UTC by yukendev

https://redmine.weseek.co.jp/issues/101970

rate limitの英語版のdocsを作成

2022-08-03 17:20 UTC, yuki-takei requested changes

2022-08-03 17:20 UTC, yuki-takei commented on docs/en/admin-guide/admin-cookbook/custom-rate-limit.md
> +For un-logged-in users, the key to restrict is a hash value of a string containing the **endpoint**, **request method**, and **IP address**.
non-logged-in なのか un-logged-in なのか統一を。

key to restrict って変な感じするなあ。この restriction についての識別子だから key to identify the user みたいなのが主語になるんじゃないだろうか。

2022-08-03 17:20 UTC, yuki-takei commented on docs/en/admin-guide/admin-cookbook/custom-rate-limit.md
> +At this time, the maximum number of requests is multiplied by the expected number of people per IP address.
the maximum number of requests には日本語での「上限キャップ」的なニュアンスは含まないんじゃないだろうか。(という心配)　単なる「最大値」になってしまうのでは。

The maximum number of requests that are allowed is ...
みたいな表現ならよさそう。

2022-08-04 10:11 UTC, yukendev commented on docs/en/admin-guide/admin-cookbook/custom-rate-limit.md
> +For un-logged-in users, the key to restrict is a hash value of a string containing the **endpoint**, **request method**, and **IP address**.
修正済み

2022-08-04 10:12 UTC, yukendev commented on docs/en/admin-guide/admin-cookbook/custom-rate-limit.md
> +At this time, the maximum number of requests is multiplied by the expected number of people per IP address.
修正済み

2022-08-08 06:55 UTC, merged