feat: G2G Transfer
weseek/growi-docs pull request #319
Opened 2023-02-07 03:41 UTC by miya

2023-02-07 08:00 UTC, yuki-takei requested changes

2023-02-07 08:00 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +### ファイルアップロード設定の優先度
このセクション何を伝えたいのか曖昧過ぎる

移行作業後、移行先の設定がどうなるのかという仕様の説明をしたいわけなので、そのような表現にする。
また、将来のことは「v6.0.5 現在では～」とか「今後のアップグレードで」みたいな説明を書かないとよくわからない。

2023-02-08 07:28 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +1. <Badge text="移行元" vertical='middle' type="warning"/> GROWI の管理画面で移行キーをコピペし、移行開始ボタン押下します。
修正しました

2023-02-08 07:28 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +## 移行先の操作フロー
修正しました

2023-02-08 07:31 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +### ファイルアップロード設定の優先度
ここは自分の仕様把握不足でした..
セクション名も微妙でしたので修正しました。表も必要そうでしたので戻しました。

2023-02-08 07:48 UTC, yuki-takei requested changes

2023-02-08 07:48 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +### <Badge text="from" vertical='middle' type="warning"/> 移行元の操作フロー
ここレベル3でいいの？

2023-02-08 07:48 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +### 移行先のファイルアップロード設定
ここレベル3でいいの？

2023-02-08 08:02 UTC, yuki-takei requested changes

2023-02-08 08:02 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +  - 添付ファイルは転送されます
この挙動は現状生きているのかを確認する

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +### 移行先のファイルアップロード設定
修正しました

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +### <Badge text="from" vertical='middle' type="warning"/> 移行元の操作フロー
修正しました

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +今後のアップデートにより **移行元** でファイルアップロード設定を選択することが可能になる予定です。
移行元でファイルアップロード設定を選択し、移行先の設定を上書きできる という表現に変更

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +    - 添付ファイルは転送されません
転送は行われず、移行元でアップロードした画像が閲覧できます という表現に変更

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +  - 添付ファイルは転送されます
移行先のファイルアップロード設定が未設定の場合は一律で添付ファイルの移行しない仕様になるのでこの項目は削除

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +    - 転送されます
未インストール時の挙動を追加

2023-02-08 17:20 UTC, miya commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +:::
warning を追加

2023-02-08 19:07 UTC, yuki-takei requested changes

2023-02-08 19:07 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/g2g-transfer.md
> +    - 転送されます
- サービス/バケット名が異なる場合は転送を行います
- サービス/バケット名が一致している場合は転送しません(転送不要で移行が完了します)

2023-02-09 02:06 UTC, merged