feat: Apply vuepress-plugin-canonical
weseek/growi-docs pull request #331
Opened 2023-04-03 06:59 UTC by miya

## Task
[#119364](https://redmine.weseek.co.jp/issues/119364) [docs-reorganization] help-growi-cloud 側で重複するページに対して canonical タグを挿入できる
└ [#119536](https://redmine.weseek.co.jp/issues/119536) 実装

2023-04-03 07:59 UTC, miya commented on docs/.vuepress/plugins/canonical/Canonical.vue
> +      : false;
(本家との差分) EXCLUDE_PATH_PATTERN にマッチしたページパスが入った時に true になる

2023-04-04 01:27 UTC, miya commented on docs/.vuepress/plugins/canonical/index.js
> +})
https://github.com/IOriens/vuepress-plugin-canonical を growi-docs 内部に fork

2023-04-04 01:27 UTC, miya commented on docs/.vuepress/plugins/canonical/index.js
> +      EXCLUDE_PATH_PATTERNS: options.excludePathPatterns || undefined,
- (本家との差分) EXCLUDE_PATH_PATTERNS というオプションを新設
- canonical タグ挿入の対象外ページパスを正規表現が内包された配列受け取る

2023-04-04 01:27 UTC, miya commented on docs/.vuepress/plugins/canonical/Canonical.vue
> +    const isExcludePath = this.isExcludePath();
(本家との差分) EXCLUDE_PATH_PATTERNS にマッチしたページパスが入った時に true になる

2023-04-04 01:27 UTC, miya commented on docs/.vuepress/config-growi-org.js
> +    ],
- 自己参照 Canonical
- help-growi-cloud で含まれないページは canonical する必要がないので除外

2023-04-04 01:27 UTC, miya commented on docs/.vuepress/config-help-growi-cloud.js
> +    ],
help-growi-cloud にのみ存在するページが入るディレクトリを仮に /Cloud としている

2023-04-04 10:55 UTC, miya commented on docs/.vuepress/plugins/canonical.js
> +})
- 任意のページパスに対して canonical tag を挿入するプラグイン
- `canonicalBase` (正規URL), 
- `excludePathPatterns` (canonical tag を挿入対象外にするパスの正規表現配列)

2023-04-04 14:42 UTC, miya commented on docs/.vuepress/plugins/canonical.js
> +})
- 任意のページパスに対して canonical tag を挿入するプラグイン
- `canonicalBase` (正規URL), 
- `excludePathPatterns` (canonical tag を挿入対象外にするパスの正規表現配列)

2023-04-04 14:42 UTC, miya commented on docs/.vuepress/config-growi-org.js
> +    ]
- help-growi-cloud と共存するページに自己参照 canonical タグを付与
- excludePathPatterns には growi-org にのみ存在するページパスを渡している

2023-04-06 06:57 UTC, yuki-takei requested changes

2023-04-06 06:57 UTC, yuki-takei commented on docs/.vuepress/plugins/canonical.js
> +})
オブジェクト化で遅くなっている可能性はないか
https://pisuke-code.com/js-ways-to-create-regexp-and-perf/

forEach 的な入れ子が「全path > excludePathPatterns」になっているという部分を疑っている。
予め excludePathPatterns を操作して RegExp オブジェクトを1回きり作っておくなり、
または config.js 側で予め正規表現リテラルの配列 or RegExp オブジェクトの配列として登録しておくなりで早くならないかな、と。

2023-04-12 01:55 UTC, miya commented on docs/.vuepress/plugins/canonical.js
> +})
あまり効果がなかったのでマージします

2023-04-12 01:55 UTC, miya commented on docs/.vuepress/plugins/canonical.js
> +})
あまり効果がなかった為修正はしませんでした。

2023-04-12 01:56 UTC, merged