feat: Adding Top page
weseek/growi-docs pull request #342
Opened 2023-04-21 07:24 UTC by miya

## Task
[#118147](https://redmine.weseek.co.jp/issues/118147) [docs-reorganization] XD 通りに Docs を表示できる
└ [#120408](https://redmine.weseek.co.jp/issues/120408) トップページ実装

2023-04-21 09:44 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +    <Top />
トップページと具体的なヘルプページの出しわけは後続タスクで行う

2023-04-21 11:36 UTC, yuki-takei requested changes

2023-04-21 11:36 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/components/Top.vue
> +      <div class="row">
このファイル中で row が一つしかないのはおかしい

2023-04-21 11:43 UTC, yuki-takei requested changes

2023-04-21 11:43 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/components/Top.vue
これってコンテンツ(各ページへのリンク)は固定なの？自動生成なの？
自動生成にできるならした方がいいと思うが開発が必要になるのか…？

2023-04-22 06:48 UTC, merged

2023-04-24 02:23 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/Top.vue
> +      <div class="row">
解決済み