feat: Add Questionnaire docs
weseek/growi-docs pull request #369
Opened 2023-05-25 10:29 UTC by jam411

task: https://redmine.weseek.co.jp/issues/116535

## Screenshot
### Japanese
![127 0 0 1_8080_ja_guide_features_questionnaire html (2)](https://github.com/weseek/growi-docs/assets/68407388/6f4b6e91-cf12-41b6-83e8-367383a62624)
![127 0 0 1_8080_ja_guide_features_questionnaire html (5)](https://github.com/weseek/growi-docs/assets/68407388/ee8be0f6-2bc6-4441-9332-592ae9d5dc9f)

------

### English
![127 0 0 1_8080_ja_guide_features_questionnaire html (1)](https://github.com/weseek/growi-docs/assets/68407388/d310c95c-413b-49a3-ae62-0cb1df372438)
![127 0 0 1_8080_ja_guide_features_questionnaire html (4)](https://github.com/weseek/growi-docs/assets/68407388/92211f8c-853c-4642-8021-4e73fd875819)

2023-05-25 10:53 UTC, yuki-takei requested changes

2023-05-25 10:53 UTC, yuki-takei commented on docs/ja/guide/features/questionnaire.md
> +v6.1.0 より GROWI にアンケート機能が追加されました。ユーザーが自由なタイミングで送信できる[能動的アンケート](/ja/guide/features/questionnaire.html#%E8%83%BD%E5%8B%95%E7%9A%84%E3%82%A2%E3%83%B3%E3%82%B1%E3%83%BC%E3%83%88)と GROWI 開発チームが事前に用意したアンケー
能動的アンケートと受動的アンケート、名前変えましょう。

> GROWI 開発チームが事前に用意したアンケートを受信して答える受動的アンケート

「GROWI 開発チームから配信されるアンケートに回答する受動的アンケート(名前は変える)」にしよう

2023-05-25 10:53 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/app-settings.md
> +このオプションにより、送信されるのは `appSiteUrlHashed` の値のみになります。
今回の差分ではないけれど、

「運用しているサイトの URL を GROWI 開発チームに対して秘匿したい場合は」

に変えましょう

2023-05-26 03:18 UTC, jam411 commented on docs/ja/guide/features/questionnaire.md
> +v6.1.0 より GROWI にアンケート機能が追加されました。ユーザーが自由なタイミングで送信できる[能動的アンケート](/ja/guide/features/questionnaire.html#%E8%83%BD%E5%8B%95%E7%9A%84%E3%82%A2%E3%83%B3%E3%82%B1%E3%83%BC%E3%83%88)と GROWI 開発チームが事前に用意したアンケー
受動的アンケートをアンケートと呼ぶことになったので、
「GROWI 開発チームから配信されるアンケートがあります。」
に修正します。
https://wsgrowi.slack.com/archives/C054BGS028P/p1685069692415289?thread_ts=1685012766.619979&cid=C054BGS028P

2023-05-26 03:18 UTC, jam411 commented on docs/ja/guide/features/questionnaire.md
> +GROWI 開発チームからのアンケートを受け取ることができます。
修正しました。

2023-05-26 03:18 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/app-settings.md
> +このオプションにより、送信されるのは `appSiteUrlHashed` の値のみになります。
修正しました。

2023-05-26 03:18 UTC, merged