feat: Hide descriptions that do not need to be displayed on the help page
weseek/growi-docs pull request #370
Opened 2023-05-29 13:54 UTC by miya

## Task
[#123287](https://redmine.weseek.co.jp/issues/123287) [docs-reorganization] docs と help で共用しているページで help では表示する必要のない記述を隠すことができる 
└

2023-05-30 03:12 UTC, miya commented on .markdownlint.json
> +  "MD033": false
https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md

2023-05-30 03:12 UTC, miya commented on docs/.vuepress/components/HiddenOnHelp.vue
> +</template>
help-growi-cloud サイトだった場合は children の内容を隠すコンポーネントを新設

2023-05-30 03:12 UTC, miya commented on docs/ja/admin-guide/management-cookbook/audit-log.md
`HiddenOnMarkdown` の使用例です。後続タスクでこのコンポーネントが必要な箇所を全てカバーします。

2023-05-30 08:43 UTC, miya commented on docs/en/admin-guide/management-cookbook/audit-log.md
> +<span v-if="!$themeConfig.isHelpGrowiCloud">
- help と docs で出し分けできるようにした
- 後続タスクで出し分け必要な箇所を全てカバーします

2023-05-30 14:46 UTC, yuki-takei requested changes

2023-05-30 14:46 UTC, yuki-takei commented on docs/en/admin-guide/management-cookbook/audit-log.md
> +<span v-if="!$themeConfig.isHelpGrowiCloud">
- ブロック要素が含まれるので span は微妙
- 今後 `isHelpGrowiCloud` という文字列が markdown に量産されるのもあまりよくない

以下のような仕様にできない？

```
<ContextualBlock context="help-growi-cloud">
## Setup
...
</ContextualBlock>
```

```
- foo
- bar
- <ContextualElement context="docs-growi-org">baz</ContextualElement >
```

因みに li を挟むなら block かな

2023-05-31 03:18 UTC, miya commented on docs/en/admin-guide/management-cookbook/audit-log.md
> +<span v-if="!$themeConfig.isHelpGrowiCloud">
ContextualBlock component を新設しました。チルドレンに `- hogehoge` を入れると list に変換されなかったので children を <li> で囲っています。

2023-05-31 04:04 UTC, merged