feat: Automatically generating the links to be displayed on the top page
weseek/growi-docs pull request #375
Opened 2023-06-06 02:50 UTC by miya

## Task
[#123288](https://redmine.weseek.co.jp/issues/123288) [docs-reorganization] Top ページに表示する全リンクを自動生成できる 
└ [#123574](https://redmine.weseek.co.jp/issues/123574) 実装

2023-06-06 16:27 UTC, miya commented on docs/.vuepress/utils/index.js
> +}
- config.js の themeConfig.links に指定した markdown ファイルのパスから markdown の h1 をタイトルとして取得するためのスクリプト
- https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/util/index.js からコードを fork
  - fork したコードのうち resolveTopPageItems だけをカスタム
  - fork したコードのうち resolveTopPageItems に依存ししているメソッドだけ残し不要なものは削除

下記のようなデータを取得できる
<img width="1166" alt="ScreenShot 2023-06-06 11 56 46" src="https://github.com/weseek/growi-docs/assets/34241526/44554492-f58a-4d90-88b8-fd1ce7c16e3f">

2023-06-06 16:27 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/Top.vue
> +    this.topPageItems = resolveTopPageItems(this.$site, 'ja');
- ここで conig.js で指定したページの全データを取得する

2023-06-06 16:27 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/Top.vue
> +    <PageLinks categoryName="Docs" :pageItems="getPageItems(['tutorial', 'tips', 'feature-introduction'])" />
- PageLinks コンポーネントの仕様例
- 残りページはマーケターやデザイナーと相談しながら配置を決めようと思っています

<img width="1110" alt="ScreenShot 2023-06-06 23 57 16" src="https://github.com/weseek/growi-docs/assets/34241526/27223dfc-3158-404a-852d-1dc89156005b">

2023-06-06 16:27 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/Top.vue
>        <!-- ▼ 共通, よくある質問 ▼  -->
- ここから下のコードは cloud のデータ投入後に削除します
- style も PageLinks コンポーネントに移したので削除予定です

2023-06-06 16:27 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/PageLinks.vue
> +    </div>
- XD によると h3 を非表示するケースがあるので `this.categoryName` が null の時は非表示にする

2023-06-06 16:27 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/PageLinks.vue
> +</style>
- Top.vue にベタ書きしていたコードをコンポーネント化

2023-06-06 23:21 UTC, yuki-takei requested changes

2023-06-06 23:21 UTC, yuki-takei commented on docs/.vuepress/utils/index.js
> + * @see https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/util/index.js
参照先が master だといつの間にかなくなっているということがあるので、commit に対する URL にしておいて

2023-06-07 00:13 UTC, miya commented on docs/.vuepress/utils/index.js
> + * @see https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/util/index.js
最新の commit に対する URL に置き換えました
https://github.com/vuejs/vuepress/blob/9044f142f9253c9d120e03abd74f12de0113cf1f/packages/%40vuepress/theme-default/util/index.js

2023-06-07 05:34 UTC, merged