123393 help page design
weseek/growi-docs pull request #379
Opened 2023-06-09 04:53 UTC by satof3

# 実装した機能
- ページ(記事)表示の雛形
  - style.scssでnavbar部分と色を定義(Topにも使うため)
- <content>のスタイル
  - <style>の`.article`で定義
- fontawesomeのバージョンアップ 5=>6

# 実装されていない機能
- 検索フォームと検索ボタンの機能
- パンくずリストの機能
- シンタックスハイライトのコードブロック(````囲み)
  - 現在はすべて`<code>`で表示されている
- CustomBlock (`:::`囲みTips Warning Danger)

![screencapture-localhost-8080-ja-guide-tips-hierarchical-html-2023-06-09-13_03_14](https://github.com/weseek/growi-docs/assets/113958844/dc37bb63-a3cc-47cc-b19d-d378bc249fbc)
![screencapture-localhost-8080-ja-guide-tips-hierarchical-html-2023-06-09-13_03_49](https://github.com/weseek/growi-docs/assets/113958844/69ab3ab1-468e-415a-af93-d600f8d72314)

2023-06-12 04:53 UTC, yuki-takei requested changes

2023-06-12 04:53 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +                <!-- TODO:検索ができるようにする -->
コメントは全て英語で

2023-06-12 04:53 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +              ヘルプ一覧に戻る
このファイルでは i18n はどうなっている？

2023-06-12 04:55 UTC, yuki-takei requested changes

2023-06-12 04:55 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +}
こんなに細かくスタイル指定する必要あるかね？ ベースは VuePress 標準でよくて、色味を growi.cloud に寄せるとかそれくらいでいいんじゃないかと思っているが。

2023-06-15 07:35 UTC, satof3 commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +                <!-- TODO:検索ができるようにする -->
検索機能取り込んだのでコメント自体が削除になりました

2023-06-15 07:35 UTC, satof3 commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +              ヘルプ一覧に戻る
i18n化は別タスクでコメント残してもらいました(Article.vue)

2023-06-15 07:39 UTC, satof3 commented on docs/.vuepress/help-growi-cloud-theme/Layout.vue
> +}
vue.jsのdefaultthemeを入れることでテーブル周りのスタイルは消えました。ただBootstrap(_reboot.scss)で上書きされてしまうためhタグmarginを設定しました。pタグは可読性を考慮しmargin-bottomを設定しました。

2023-06-15 09:17 UTC, miya commented on docs/.vuepress/styles/arrow.styl
ここから下は全て VuePress 公式のコードを fork したものです

2023-06-16 05:00 UTC, miya commented on docs/.vuepress/styles/arrow.styl
> +// forked: https://github.com/vuejs/vuepress/blob/9044f142f9253c9d120e03abd74f12de0113cf1f/packages/%40vuepress/theme-default/styles/arrow.styl
- ここから下の差分は VuePress 公式の style を fork したものです
- `/docs/.vuepress/help-growi-cloud-theme` に移動しても良さそうです

2023-06-20 07:27 UTC, merged