support: Mobile view
weseek/growi-docs pull request #385
Opened 2023-06-15 02:16 UTC by miya

## Task
[#118147](https://redmine.weseek.co.jp/issues/118147) [docs-reorganization] XD 通りにヘルプページを表示できる
└ 124388 SP 版対応

2023-06-19 05:52 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/GlobalHeaderMenu.vue
> +</style>
style の共通化などのリファクタは見た目の実装があらかた終了次第行います。

2023-06-19 11:35 UTC, yuki-takei requested changes

2023-06-19 11:35 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/components/Header.vue
> +  z-index: 1300;
1300 の根拠をコメントで追加

2023-06-19 11:35 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/components/Header.vue
> +  z-index: 1299;
1299 の根拠をコメントで追加

2023-06-19 11:35 UTC, yuki-takei commented on docs/.vuepress/help-growi-cloud-theme/components/GlobalHeaderMenu.vue
> +  -webkit-appearance: none;
vendor prefix は消す
消されたら困るならアーキテクトのタスクとして postcss を設定する(後続ストーリーでもよい)

2023-06-20 02:45 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/Header.vue
> +  z-index: 1300;
追加しました

2023-06-20 02:45 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/Header.vue
> +  z-index: 1299;
追加しました

2023-06-20 02:45 UTC, miya commented on docs/.vuepress/help-growi-cloud-theme/components/GlobalHeaderMenu.vue
> +  -webkit-appearance: none;
消しました

2023-06-20 02:46 UTC, merged