feat: Create Dockerfile
weseek/growi-docs pull request #387
Opened 2023-06-21 14:26 UTC by miya

[#125219](https://redmine.weseek.co.jp/issues/125219) Dockerfile の作成

2023-06-22 13:53 UTC, miya commented on docs/.vuepress/config-help-growi-cloud.js
> +  base: '/help/',
バンドルされた js が正常に読み込まれない箇所があったため修正

2023-06-22 13:53 UTC, miya commented on Dockerfile
> +RUN rm -rf /usr/share/nginx/html/help/assets/images
js, css ファイルは /help/assets/ を参照しているが、画像のみ /assets を参照しており正常に画像が読み込まれなかったため 23, 24 行目を追加しました

2023-06-23 08:46 UTC, yuki-takei requested changes

2023-06-23 08:46 UTC, yuki-takei commented on Dockerfile
> +FROM node:16-alpine AS builder
node:16-slim か node:18-slim に統一したほうがいい

2023-06-23 08:46 UTC, yuki-takei commented on Dockerfile
> +RUN rm -rf /usr/share/nginx/html/help/assets/images
builder で先に消しとけば？

2023-06-23 09:19 UTC, merged