128344-106002-GROWI.cloud における二要素認証について help に記載
weseek/growi-docs pull request #416
Opened 2023-08-22 06:00 UTC by takahiro-k11

2023-08-22 06:01 UTC, takahiro-k11 commented
<img width="984" alt="image" src="https://github.com/weseek/growi-docs/assets/89763543/180bdd5d-32d5-436a-872a-387e3e67d229">

2023-08-22 06:01 UTC, takahiro-k11 commented
<img width="866" alt="image" src="https://github.com/weseek/growi-docs/assets/89763543/488f9e66-6bcf-4732-98c0-fb9ca36dbf33">

2023-08-22 06:04 UTC, takahiro-k11 commented
セキュリティ設定ページに
二要素認証の項目を追加
https://growi.cloud/help/ja/admin-guide/management-cookbook/security.html

2024-05-13 08:44 UTC, TatsuyaIse commented
<img width="725" alt="image" src="https://github.com/weseek/growi-docs/assets/8895367/e8d82064-535d-44ae-ba0d-3f8b9875810d">
<img width="728" alt="image" src="https://github.com/weseek/growi-docs/assets/8895367/c9cb3c35-2730-49b6-836d-a798522c5b10">


![image](https://github.com/weseek/growi-docs/assets/8895367/4a4a87f3-ae00-462e-91f0-014f9afccb72)

![image](https://github.com/weseek/growi-docs/assets/8895367/64d27bfb-6de9-4b48-8327-f795531eb066)

2024-05-14 01:19 UTC, skomma requested changes

2024-05-14 01:19 UTC, skomma commented on docs/en/cloud/cloud-mfa-login.md
> +  Our service does not provide two-factor authentication log in.
```suggestion
  Our service does not provide two-factor authentication login feature.
```
ログイン自体を提供していないわけではなく、機能を提供してないから。

2024-05-14 01:19 UTC, skomma commented on docs/en/cloud/cloud-mfa-login.md
> +  However, you can log in to GROWI.cloud using an external service account that allows you to set up two-factor authentication.
```suggestion
  However, using an external service account(Google, GitHub account) enables two-factor authentication login.
```
なんか長いし、具体的なサービス名は削らなくてもよいのでは、という気が。

2024-05-14 01:19 UTC, skomma commented on docs/ja/cloud/cloud-mfa-login.md
> +  二要素認証を設定済みの外部サービスアカウントを用いて GROWI.cloud にご登録いただくことで、副次的に GROWI.cloud のログインに二要素認証をご利用いただけていると言えます。
```suggestion
  二要素認証を設定済みの外部サービスアカウントを用いて GROWI.cloud にご登録いただくことで、副次的に GROWI.cloud のログインに二要素認証をご利用いただけます。
```
回りくどい。

2024-05-14 01:19 UTC, skomma commented on docs/en/cloud/cloud-mfa-login.md
> +  it is the same as using two-factor authentication to log in to GROWI.cloud.
```suggestion
  By registering an external service account with two-factor authentication already enabled,
  you can log in to GROWI.cloud using two-factor authentication.
```
「見なす」という言い回し、必要かねぇ？

2024-05-14 01:19 UTC, skomma commented on docs/en/cloud/cloud-mfa-login.md
> +### Help page regarding two-factor authentication for each service
```suggestion
### How to set up an external account to enable two-factor authentication
```
英文では、`How to` の方がよく見る表現かなぁ。

2024-05-14 01:19 UTC, skomma commented on docs/ja/cloud/cloud-mfa-login.md
> +### 各サービスのヘルプページは以下となります
```suggestion
### 各サービスの二段階認証に有効化手法
```
日本語は他のヘルプページがどうなってるか知らないので、任せる。

2024-05-14 01:23 UTC, skomma requested changes

2024-05-14 01:23 UTC, skomma commented on docs/.vuepress/config-help-growi-cloud.js
> +            '/en/cloud/cloud-mfa-login.md',
細かいけど、ファイル名と題名は合わせたほうがよくない？
Two-Factor Authentication と Multi-Factor Authentication じゃ言ってること違うんだが。

2024-05-14 02:53 UTC, TatsuyaIse reviewed
suggest していただいた分はすべて取り込ませてもらいました！

2024-05-14 02:53 UTC, TatsuyaIse commented on docs/en/cloud/cloud-mfa-login.md
> +  Our service does not provide two-factor authentication log in.
naruhodo

2024-05-14 02:53 UTC, TatsuyaIse commented on docs/en/cloud/cloud-mfa-login.md
> +  However, you can log in to GROWI.cloud using an external service account that allows you to set up two-factor authentication.
そうですね、、

2024-05-14 02:53 UTC, TatsuyaIse commented on docs/en/cloud/cloud-mfa-login.md
> +  it is the same as using two-factor authentication to log in to GROWI.cloud.
たしかに？

2024-05-14 02:53 UTC, TatsuyaIse commented on docs/en/cloud/cloud-mfa-login.md
> +### Help page regarding two-factor authentication for each service
そうですね、

2024-05-14 02:53 UTC, TatsuyaIse commented on docs/ja/cloud/cloud-mfa-login.md
> +### 各サービスのヘルプページは以下となります
前任の実装者が残していた表現に引っ張られてしまいました。  
変えたほうが良さそうなので取り込みます！ありがとございます

2024-05-14 02:53 UTC, TatsuyaIse commented on docs/.vuepress/config-help-growi-cloud.js
> +            '/en/cloud/cloud-mfa-login.md',
ズレてはだめですね、、修正します。

2024-05-14 05:31 UTC, TatsuyaIse commented on docs/.vuepress/config-help-growi-cloud.js
> +            '/en/cloud/cloud-mfa-login.md',
`cloud-tfa-login` に修正しました

2024-05-14 05:38 UTC, skomma approved these changes

2024-05-14 05:38 UTC, merged