support: revise guide for presentation and marp
weseek/growi-docs pull request #424
Opened 2023-09-19 06:34 UTC by moekumasaka

https://redmine.weseek.co.jp/issues/130859

2023-09-21 12:04 UTC, yuki-takei requested changes

2023-09-21 12:04 UTC, yuki-takei commented on docs/ja/guide/features/presentation.md
> +---
`slide: true` では下の方でも書いている「Markdown で記載されたページの見出しごとにスライドが自動で作成されます。 (対象の見出しは h1(#) と h2(##) です。)」の挙動によりスライドの区切りはヘッダーごとになるので、区切り線は不要。

2023-09-21 12:04 UTC, yuki-takei commented on docs/ja/guide/features/presentation.md
> +プレゼンテーション機能を使う場合は、特別な設定や編集をする必要はありません。スライドショーを開始すると、自動で Markdown の内容をスライド化します。View モードや編集モードのプレビューでスライドを表示したい場合は、[スライドビュー機能](/ja/guide/features/presentation.html#view-モードや編集モードのプレビューでスライドを表示する)
プレゼンテーション機能への言及はここには相応しくないのではないか。

2023-09-22 00:38 UTC, moekumasaka commented on docs/ja/guide/features/presentation.md
> +スライドビュー機能を利用するためには、ページ内の Frontmatter に `slide: true` を記載します。(v6.2.0以降、Frontmatter はプレビューや View モードでは表示されません。)
Frontmatter ページの作成は以下のタスクで対応する
https://redmine.weseek.co.jp/issues/131166

2023-09-22 02:30 UTC, moekumasaka commented on docs/ja/guide/features/presentation.md
> +プレゼンテーション機能を使う場合は、特別な設定や編集をする必要はありません。スライドショーを開始すると、自動で Markdown の内容をスライド化します。View モードや編集モードのプレビューでスライドを表示したい場合は、[スライドビュー機能](/ja/guide/features/presentation.html#view-モードや編集モードのプレビューでスライドを表示する)
GROWI スライドを使う(作る？)ケースは
プレゼンテーション機能を使うとき
スライドビューするとき
の2パターンあって、
のときは設定や編集不要
のときは slide: true にする
というのが「使い方」にあたるかなと思って書きました

2023-09-25 02:46 UTC, merged