Update User homepage deletion
weseek/growi-docs pull request #441
Opened 2023-11-24 12:49 UTC by jam411

https://redmine.weseek.co.jp/issues/134610

# ja
![image](https://github.com/weseek/growi-docs/assets/68407388/cbb34840-2b3f-4b52-9c86-edd723e9760a)

# en
![image](https://github.com/weseek/growi-docs/assets/68407388/7459a6de-cca2-49b8-842c-6ca4f5fa2889)

2023-11-27 10:12 UTC, miya commented on docs/ja/admin-guide/management-cookbook/security.md
> +削除済みユーザーのユーザーホームページ（`/user/{username}`）を通常ページ同様に削除または完全削除されるようになります。
される -> できる の方が個人的に違和感がありませんでした

2023-11-27 10:12 UTC, miya commented on docs/ja/admin-guide/management-cookbook/security.md
> +ユーザーを削除する際に、ユーザーホームページ（`/user/{username}`）とその配下のページも完全削除されます。無効にしている場合は、ユーザーを削除してもユーザーホームページは削除されません。
これも個人的な感想ですが、warning の中に入れても良いレベルだと思いました

2023-11-27 10:21 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/security.md
> +ユーザーを削除する際に、ユーザーホームページ（`/user/{username}`）とその配下のページも完全削除されます。無効にしている場合は、ユーザーを削除してもユーザーホームページは削除されません。
こちら管理画面にこれ用のチェックボックスがあるので外に出したままにします 🙏

2023-11-30 07:19 UTC, yuki-takei requested changes

2023-11-30 07:19 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/security.md
> +ごみ箱（`/trash`）にあるユーザーホームページはこの設定に関係なく完全削除が可能です。
「一度ごみ箱（`/trash`）にあるユーザーホームページは」に変えよう

2023-11-30 07:19 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/security.md
- 2つのセクションのタイトルに、「自動 (automatically)」「手動 (manually)」っていう単語を入れた方がいい気がする
    - 差異が直感的にわかるように
- セクションの順序を、自動が先、手動が後になるように入れ替えた方がよくないか？(提案)
    - 自動削除のオプションがオフになっていてそのまま放置されたユーザーホームページをあとから手動で削除することになると思うので

2023-11-30 07:41 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/security.md
セクションの順序は、意図としては管理画面に従った順番にしていて、docs と順序を変えるとわかりにくくなるかなと思ったのですがいかがでしょうか？ 👀

2023-11-30 08:31 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/security.md
> +ごみ箱（`/trash`）にあるユーザーホームページはこの設定に関係なく完全削除が可能です。
/trash 配下にある場合は設定にかかわらず完全削除可能であることを記載したかったのですが、"一度" とはどういうニュアンスでしょうか？
例えばユーザーホームページを削除して(/trash/user/{username}) へ移動したあと、「ページを元に戻す」で /user/{username} に戻します。戻したページを再び削除を試みたとき、設定で手動削除できないようにしていれば手動でのユーザーホームページの削除ができなくなります。

2023-11-30 10:21 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/security.md
ああああ、そっか。勘違いしてたかもしれん

管理画面こうだよね。
![image](https://github.com/weseek/growi-docs/assets/1638767/bcf108a7-4b9c-4f34-a295-b7c1f53e68e0)

2023-12-01 09:04 UTC, merged