imprv: ldap and keycloak group sync
weseek/growi-docs pull request #442
Opened 2023-12-06 06:15 UTC by AikaHiyama

2023-12-06 07:04 UTC, jam411 requested changes

2023-12-06 07:04 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +- 登録エンドポイント: <http://host.docker.internal:8080/realms/myrealm/clients-registrations/openid-connect>
このあたりの `host.docker.internal:8080/realms/myrealm` は環境に依存するので、例として書くのはいいかもですが、書きたくないです。
設定例を別項目で用意するのはいいともいますが、基本は「下記項目の設定が必要です」レベルにシンプルにしたいです。
もしくは各項目の説明を書くなどですが、難しいので書かなくていいと思います。

2023-12-06 07:07 UTC, jam411 requested changes
構成としては、
- LDAP か Keycloak を選ぶ
- 設定をする
　- LDAP なり keycloak の認証機構設定しないといけませんと書く
　- それぞれ設定項目について説明を書く
- 同期ぼたんを押す
  - 同期時の注意を書く(大規模同期時にどうなるかとか、途中でページ遷移してもできるとか）

2023-12-08 02:42 UTC, jam411 requested changes

2023-12-08 02:42 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +4. 同期されたユーザでログインし、グループに所属していることを確認してください
これは動作確認内容であり、Docs に書くべきは使い方なので不要です。

2023-12-08 02:42 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +1. GROWI 管理画面のグループ管理画面(/admin/user-groups)にアクセスし、作成したい外部グループ（LDAP または Keycloak）のタブを選択します
path は `/admin/user-groups` とバッククオートで囲って書いてください。

2023-12-08 02:42 UTC, jam411 commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +- 子グループを表す LDAP 属性
以下のリストは何であるのか文章から読み取れないので、
「必須項目は以下です。」
のように何であるのを記載してください。
```
- グループ検索ベース DN
- 所属メンバーを表す LDAP 属性
- 子グループを表す LDAP 属性
```

2023-12-20 08:36 UTC, yuki-takei requested changes

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +LDAPとkeycloakのグループ同期とは、 LDAPやKeycloak がもつ外部グループ情報を同期する機能です。
Keycloak の大文字小文字を統一してください。(これ以降も揺らぎがある)

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +LDAPとkeycloakのグループ同期とは、 LDAPやKeycloak がもつ外部グループ情報を同期する機能です。
概要に関してはアップグレードガイドから表現を拝借し、統一に努めてください。

https://docs.growi.org/ja/admin-guide/upgrading/63x.html#ldap-keycloak-%E3%81%8B%E3%82%89%E3%81%AE%E3%83%A6%E3%83%BC%E3%82%B5%E3%82%99%E3%83%BC%E3%83%BB%E3%83%A6%E3%83%BC%E3%82%B5%E3%82%99%E3%83%BC%E3%82%AF%E3%82%99%E3%83%AB%E3%83%BC%E3%83%95%E3%82%9A%E3%81%AE%E3%82%A4%E3%83%B3%E3%83%9B%E3%82%9A%E3%83%BC%E3%83%88%E3%81%8A%E3%82%88%E3%81%B2%E3%82%99%E5%90%8C%E6%9C%9F-%E3%83%98%E3%82%99%E3%83%BC%E3%82%BF

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +ユーザーの所属グループ情報が一貫して管理できるため、ユーザーやグループを再登録する必要がなく、手軽にグループ機能を活用できます。
概要と内容が同じなのでこのセクションは廃止でよい。

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +外部認証プロバイダー（LDAPやKeycloak）が提供するセキュリティ機能を活用することで、認証や認可の信頼性が向上します。
認証プロバイダーを外部化するメリットはグループ同期機能の特徴とはずれるのでこのセクションは廃止でよい。

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +## GROWI 側の必要な設定
GROWI 側で必要な設定

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +### LDAP
`2. 選択した認証機構の設定をします` の中にセクションを入れるのは markdown 的に歪だと思う。構成や章立ての手段を見直してください。

2023-12-20 08:36 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +3. 同期実行の「同期」をクリックし、「外部グループ管理」内の「グループ一覧」にグループが追加されていることを確認します
- 設定と同期実行はセクションを分けてください
- 同期実行した時の具体的な挙動をもっと詳しく説明すべき
- 2回目以降の同期実行時の具体的な挙動をもっと詳しく説明すべき
    - LDAP/Keycloak 側のデータに変更があった時にどうなるのか
    - slack で futa-a にヒアリングしてほしい

2023-12-22 11:25 UTC, yuki-takei requested changes

2023-12-22 11:25 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +またこの機能は、一度インポートしたユーザーおよびユーザーグループに対する変更を追跡し、同期させることもできます。
ここ、前に指示した通りに入れてもらったとは思いますが齟齬があったので書き換えをお願いします、すみません。

> GROWI v6.3 では、外部システムで管理しているユーザーとユーザーグループのデータを GROWI にインポートできる機能を搭載しました。  
> インポートは LDAP サーバーまたは Keycloak から選択できます。LDAP と連携した Keycloak も対象になります。  
> またこの機能は、一度インポートしたユーザーおよびユーザーグループに対する変更を追跡し、同期させることもできます。

2023-12-22 11:25 UTC, yuki-takei commented on docs/ja/admin-guide/management-cookbook/ldapandkeycloakgroupsync.md
> +1. GROWI 管理画面のセキュリティ設定画面(`/admin/security`)にアクセスし、「認証機構設定」内、「LDAP」タブから設定します。
HTML にした時にこの行をもっと目立たせる必要がある。`###` (サブセクション) にした方がいいかもしれない。

2023-12-27 11:28 UTC, yuki-takei requested changes

2024-01-23 12:25 UTC, merged