feat: Built-in collaborative editor
weseek/growi-docs pull request #451
Opened 2024-03-27 11:18 UTC by miya

## Task
[#137019](https://redmine.weseek.co.jp/issues/137019) [v7][New Editor][collab][autosave][Docs] 同時多人数編集について Docs 作成する
┗ [#143213](https://redmine.weseek.co.jp/issues/143213) Docs 執筆

## Screenshot
![screencapture-localhost-8080-ja-guide-features-built-in-editor-html-2024-03-27-20_31_33](https://github.com/weseek/growi-docs/assets/34241526/cbb51686-953c-48da-b648-838595d205f0)

2024-03-28 14:59 UTC, yuki-takei requested changes

2024-03-28 14:59 UTC, yuki-takei commented on docs/ja/guide/features/built-in-editor.md
> +エディターに入力された文字はドラフトとして保存されます。ページを更新せずに離脱してもそのページのドラフトは残り続けます。
エディターでの編集内容はドラフト(下書き)データとして自動でサーバーに保存されます。ページを更新せずに離脱してもそのページのドラフトは残り続けます。

2024-03-28 14:59 UTC, yuki-takei commented on docs/ja/guide/features/built-in-editor.md
> +## ページ更新時の注意点
このセクションを内部仕様まで含め真面目に解説するかどうかは難しいなあ

> ユーザーがページの更新の際に最新のページデータ必要かそうでない場合があります

こんなこと言われても意味不明だと思う。


## 伝えたい内容

- 更新処理を受け付けないケースがある
    - ケースをどこまで詳細に説明するかは要検討
    - その場合はコンフリクト扱いになる
        - こんなアラートが出る
        - 解消が必要(この後のセクションへの誘導)

2024-03-28 14:59 UTC, yuki-takei commented on docs/ja/guide/features/built-in-editor.md
> +コンフリクトが発生するとエディター下部にアラートが表示されます。アラート内の「衝突を解消」ボタンを押すことでコンフリクト解消モーダルが表示されます。
ユーザーが取り得る手段の整理をしたいんだけど、ページリロードするとどうなるんだっけ？それもひとつの解消手段になる？

2024-03-29 10:45 UTC, miya commented on docs/ja/guide/features/built-in-editor.md
> +コンフリクトが発生するとエディター下部にアラートが表示されます。アラート内の「衝突を解消」ボタンを押すことでコンフリクト解消モーダルが表示されます。
ページリロードもコンフリクト解消手段の一つでしたので追記しました

2024-03-29 10:45 UTC, miya commented on docs/ja/guide/features/built-in-editor.md
> +## ページ更新時の注意点
修正しました。

2024-03-29 12:42 UTC, yuki-takei requested changes

2024-03-29 12:42 UTC, yuki-takei commented on docs/ja/guide/features/built-in-editor.md
> +以下のアラートが出ている場合、ページの更新手段によってはページデータが最新状態でないとページの更新ができない場合があります。アラート内の「最新版を読み込む」ボタンをクリックするかページをリロードすることでページの最新化ができます。
> ページデータが最新状態でないと

これ消そう。内部仕様わかる人じゃないとわけがわからない

2024-03-29 12:42 UTC, yuki-takei commented on docs/ja/guide/features/built-in-editor.md
> +ページ更新ができないケースでページを更新を試みた場合、コンフリクトが発生します。コンフリクトの解消方法は [コンフリクトを解消する](/ja/guide/features/built-in-editor.html#コンフリクトを解消する) を参考にしてください。
このセクションの内容は hiromu-t と協議

2024-04-03 10:31 UTC, merged