Update docs (management-cookbook/security.html)
weseek/growi-docs pull request #499
Opened 2024-05-28 09:37 UTC by reiji-h

# Summary
- /management-cookbook/security.html の更新

# Task
- https://redmine.weseek.co.jp/issues/147196

# Screenshot
## Docs ja

## Docs en

## Help ja

## Help en

2024-05-29 03:07 UTC, miya requested changes
不要になった画像は削除しよう

2024-05-29 03:07 UTC, miya commented on docs/en/admin-guide/management-cookbook/security.md
> -<img :src="$withBase('/assets/images/security.png')" alt="security">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/en/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/register.png')" alt="">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/en/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/in-app-notification-requested-registration-approval.png')" alt="">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/en/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/user-management-user-approval-pending.png')" alt="">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/ja/admin-guide/management-cookbook/security.md
> -<img :src="$withBase('/assets/images/security.png')" alt="security">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/ja/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/in-app-notification-requested-registration-approval.png')" alt="">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/ja/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/user-management-user-approval-pending.png')" alt="">
画像を削除する

2024-05-29 03:07 UTC, miya commented on docs/ja/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/register.png')" alt="">
画像を削除する

2024-05-31 03:02 UTC, reiji-h commented on docs/en/admin-guide/management-cookbook/security.md
> -<img :src="$withBase('/assets/images/security.png')" alt="security">
削除しました

2024-05-31 03:02 UTC, reiji-h commented on docs/en/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/register.png')" alt="">
削除しました。

2024-05-31 03:03 UTC, reiji-h commented on docs/en/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/in-app-notification-requested-registration-approval.png')" alt="">
削除しました

2024-05-31 03:03 UTC, reiji-h commented on docs/en/admin-guide/management-cookbook/security.md
> -  <img :src="$withBase('/assets/images/user-management-user-approval-pending.png')" alt="">
削除しました

2024-05-31 03:14 UTC, merged